# Generated by Django 5.1.3 on 2024-11-18 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_comuna_region_perfil_comuna_alter_inmueble_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
